### ISSUE TITLE
Add example for loading separate files

### ISSUE THREAD

**Issue by yperess** [javagl/ObjSamples#1]
Sorry, this is more of a request than an issue, but I can't seem to label it as such. I'm looking at using this library to load Google Poly zip files which usually come with a `*.obj`, `*.png`, and `*.mtl` files. I found that I can load the MTL files using `MtlReader.read(InputStream)` but I don't see how to combine everything into the final object. Any examples for loading these would be greatly appreciated.

**Comment by javagl** [comment]
There is no "data structure" that *combines* the OBJ and MTL in any way. The OBJ file may refer to the MTL file, and after you have read an OBJ, you can obtain the MTL file names that it refers to, using `obj.getMtlFileNames();`. (in most cases this will only be one, but the OBJ spec allows multiple, so it is a `List`). You can then read the corresponding MTL objects, using the `MtlReader`.

Eventually *combining* the `Obj` and `Mtl` objects is up to the renderer or user. In a recent issue, I sketched an example that *might* answer some of your questions: https://github.com/javagl/Obj/issues/4#issuecomment-356424533 . The most relevant part of the code is summarized here:

        // Read the MTL files that are referred to from the OBJ, and
        // extract all their MTL definitions
        List<String> mtlFileNames = obj.getMtlFileNames();
        List<Mtl> allMtls = new ArrayList<>();
        for (String mtlFileName : mtlFileNames)
        {
            InputStream mtlInputStream = context.getAssets().open(mtlFileName);
            List<Mtl> mtls = MtlReader.read(mtlInputStream);
            allMtls.addAll(mtls);
        }

        // Obtain the material groups from the OBJ, and create renderers for
        // each of them
        Map<String, Obj> materialGroupObjs =
            ObjSplitting.splitByMaterialGroups(obj);
        for (Map.Entry<String, Obj> entry : materialGroupObjs.entrySet())
        {
            String materialName = entry.getKey();
            String textureFileName = findTextureFileName(materialName, allMtls,
                defaultTextureFileName);
            Obj materialGroupObj = entry.getValue();
            createRenderers(context, materialGroupObj, textureFileName);
        }
    }

    private String findTextureFileName(String materialName,
        Iterable<? extends Mtl> mtls, String defaultTextureFileName)
    {
        for (Mtl mtl : mtls)
        {
            if (Objects.equals(materialName, mtl.getName()))
            {
                return mtl.getMapKd();
            }
        }
        return defaultTextureFileName;
    }

This is only an example. Depending on the renderer, you could solve some parts of this (e.g. figuring out the PNG file name) differently. But I think that is shows the most important steps:

- For a given `Obj`, find the MTL file names that it refers to
- Load these MTL files, to obtain the `Mtl` objects
- Figure out the "material groups" of the OBJ - namely, the parts of the OBJ that use the material that is defined in a `Mtl`. 


The connection between the "material group" in an OBJ and the actual Material that is defined in an MTL is established solely by the material name. For example, the MTL file contains a `newmtl material0`. The OBJ file contains lines like

      usemtl material0
      f 1/1/1 2/2/1 6/4/1
      ...

The `usemtl` here starts a "material group", meaning that all subsequent faces belong to the group that should be rendered with `material0`. The call

      Map<String, Obj> materialGroupObjs = ObjSplitting.splitByMaterialGroups(obj);

returns a map that maps material names to the parts of the OBJ that use this material.

(It could make sense to store the materials in a `Map<String, Mtl>` as well, mapping the material names to the `Mtl` objects. But one would have to think about the case of multiple materials that have the same name...)

**Comment by javagl** [comment]
(But nevertheless, I can add an example here in the `ObjSamples` project that shows this workflow, omitting the part that actually creates a renderer)

**Comment by yperess** [comment]
Thanks! That clears it up a lot! Sorry, I'm very new to OpenGL and `.obj` files and was asked to put together a demo for ARCore.

**Comment by javagl** [comment]
@yperess You may have noticed that the issue that I linked to was actually reported in the Google ARCore demo: https://github.com/google-ar/arcore-android-sdk/issues/73 

The `ComplexObjectRenderer` that I posted in https://github.com/javagl/Obj/issues/4#issuecomment-356424533 should be easy to integrate into the ARCore demo. 

(I did this locally, but since I don't have a real AR-Capable device, I had to strip some AR-related parts from the demo, and thus cannot test it properly here - I only tested the *rendering* path)

**Comment by yperess** [comment]
Thanks, I got things mostly working, though all my materials are coming out too white. I have one specifically that all the materials only list Ka and Kd values, so my main issue right now is writing a renderer to handle these Mtl objects. I can't seem to quite get it right. Here's what I have so far... https://stackoverflow.com/questions/48709754/fragment-shader-for-mtl-files?noredirect=1#comment84422919_48709754

**Comment by javagl** [comment]
The `ComplexObjectRenderer` just splits the OBJ and forwards the parts to the `ObjectRenderer` instances. The `ObjectRenderer` is the original class of the AR demo (now located at https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/helloar/rendering/ObjectRenderer.java ). 

Admittedly, I did not (yet) read the `ObjectRenderer` (and associated shader code) thoroughly. It might be that this is not "tweaked" for objects *without* textures. But it might also be that you changed some things in the fragment shader that cause this behavior. 

From a **short** glance: I've seen

    uniform vec2 u_MaterialParameters;
    ...
    float materialSpecularPower = u_MaterialParameters.x;
    float materialAlpha = u_MaterialParameters.y;

in the fragment shader that you posted on stackoverflow. The [original shader code of the demo](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/res/raw/object_fragment.shader) uses

    float materialAmbient = u_MaterialParameters.x;
    float materialDiffuse = u_MaterialParameters.y;
    float materialSpecular = u_MaterialParameters.z;
    float materialSpecularPower = u_MaterialParameters.w;

and this is eventually filled by calling https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/helloar/rendering/ObjectRenderer.java#L258 

So for me, it is not clear *what* you modified *where* (in the `ObjectRenderer` and in the shader code). 

Or to put it that way, naively: Doesn't it work when you use the **original** `ObjectRenderer` and shader code? (The fact that they model the material properties as single values, and not as RGB values as they are contained in an MTL file may be a caveat, but this should be unrelated to the *brightness* of the object)

**Comment by yperess** [comment]
No, the original `ObjectRenderer` doesn't work when a texture file is missing. Basically what they're doing is using a single float for the ambient, diffuse, and specular values, whereas real material descriptions should have 3 values for RGB. I took those values out of the material parameters and created 3 new parameters for ambient (Ka), diffuse (Kd), and specular (Ks). I pass the specular power and alpha via the `vec2` material parameters. More so, the ARCore example doesn't change the Ka, Kd, and Ks values depending on the material file values, they're always constant. So after you've clarified how to use the `Mtl` objects I was able to add them as parameters and pass them to the shader script, but like I said, they come out too bright which I'm sure is an issue with my shader math adding up too many light values or possibly starting off with the wrong base color.

**Comment by javagl** [comment]
I'm not sure whether I can offer any *quick* (!) and profound help here. I have implemented some basic shaders, but mostly based on tutorials (for example, I have never wrapped my head around this "gamma correction" thingy...). So I probably would need to try and 1. get your current `ObjectRenderer`+Shader-combination running and 2. do some "trial and error" to figure out what causes this wrong brightness. From a quick glance, I wonder where the difference in 

    if (u_TextureValid) {
        gl_FragColor.rgb = pow(objectColor.rgb + ambient + diffuse + specular, vec3(kGamma));
    } else {
        gl_FragColor.rgb = pow(objectColor.rgb * (ambient + diffuse) + specular, vec3(kGamma));
    }

comes from. But that's probably just me - I don't have all the lighting formulas and computations readily available and cannot say what's "right" or "wrong" by just looking at it.

(Although I could try to allocate some time for that and try it out (and this would actually fit nicely to my task to create an Android-based renderer for JglTF), it may be more likely that someone on stackoverflow provides a quicker, more focussed answer...)

**Comment by yperess** [comment]
I'd be more than happy to join forces and help create a generic Android renderer for these as I've yet to find a suitable one.

Also, that `if...else...` is where I'm super fuzzy on. It was mostly just trial and error and it's still not really working well. The reason for the addition in valid textures was because I noticed that a lot of times the ambient and diffuse values were 0 when a bitmap was present. So doing the multiply would zero it out and make it black, I'm not sure what the right way is but this made it work.

I just found a way to make things work for me, if I get rid of the gamma correction for the material without the bitmap texture and only use the diffuse it looks right. I spoke with my team, we're gonna open source our renderers tomorrow to try and get a better one going with the community. I'd love to get your help/input. I'll post a link once it's up.

**Comment by javagl** [comment]
I added an example showing the basic workflow for combining the MTL and OBJ information in order to render it with OpenGL at https://github.com/javagl/ObjSamples/blob/master/src/main/java/de/javagl/obj/samples/ObjSample_13_RenderByMaterial.java

**Comment by Panfred** [comment]
@yperess can you please publish the link of the open sourced renderers of yours? Thanks, that would help us a lot!

**Comment by yperess** [comment]
@Panfred sure thing. Give me a few days. I'm in the middle of a really big release at work.

**Comment by yperess** [comment]
@Panfred Here's what we're using at the moment. Keep in mind that this may and will most likely change drastically. What you'll see here is a demo `app` and the `obj` library. There are a few things we're toying around with and are incomplete, but the idea is to create an annotation processor that will ease in creation of models by code instead of loading an obj model. To start things off you'll be using the `ObjExtractor` class's various `load` static functions. From these you'll get back an `ObjRenderer` which will allow you to render your model. We abstract this away into a `VirtualObject` which internally we've been able to render regular Android views: ImageView, TextView, etc in 3d. This will be added to the library soon-ish.

**Comment by yperess** [comment]
@Panfred Here's what we're using at the moment. Keep in mind that this may and will most likely change drastically. What you'll see here is a demo app and the obj library. There are a few things we're toying around with and are incomplete, but the idea is to create an annotation processor that will ease in creation of models by code instead of loading an obj model. To start things off you'll be using the ObjExtractor class's various load static functions. From these you'll get back an ObjRenderer which will allow you to render your model. We abstract this away into a VirtualObject which internally we've been able to render regular Android views: ImageView, TextView, etc in 3d. This will be added to the library soon-ish.

https://github.com/GoMeta/android-support-obj-render/

**Comment by javagl** [comment]
@yperess Sorry, my intention by opening the issue was not to force you to take down the whole repo. I hope you didn't take toooo much offense in that. (Any maybe I should mention that I appreciated your contributions and feedback here).

I think that it would generally be appreciated if you revived the repo when the issue is resolved.

**Comment by yperess** [comment]
@javagl no offense at all. You're 100% correct in that issue and it was an unfortunate issue. I was using your library to understand the file format and was trying to create a more in place algorithm. Time and deadlines came so I quickly imported your code which automatically reassigned the package name and added the copyright. This is **not** ok and I feel stupid for not noticing. Once resolved I'll bring the repo back up.
